# Generated by Django 2.1.2 on 2019-07-05 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('calorie', models.FloatField(null=True)),
                ('count', models.FloatField(default=0, null=True)),
                ('measurementUnit', models.CharField(max_length=200, null=True)),
                ('isVegetarian', models.CharField(max_length=3, null=True)),
                ('amountsOfGram', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('subtitle', models.CharField(max_length=200, null=True)),
                ('calorie', models.FloatField(default=0, null=True)),
                ('count', models.CharField(max_length=200, null=True)),
                ('measurementUnit', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeasureTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('object_type', models.CharField(max_length=200, null=True)),
                ('technical_measure', models.FloatField(null=True)),
                ('measurementUnit', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('calorie', models.FloatField(default=0, null=True)),
                ('text', models.TextField(null=True)),
                ('score', models.IntegerField(default=0, null=True)),
                ('isHard', models.CharField(max_length=50, null=True)),
                ('isVegetarian', models.CharField(max_length=3, null=True)),
                ('isGood', models.CharField(max_length=3, null=True)),
                ('image', models.ImageField(null=True, upload_to='photos')),
                ('isTrain', models.CharField(max_length=10, null=True)),
                ('technical_type', models.CharField(max_length=200, null=True)),
                ('time', models.CharField(max_length=10, null=True)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VegetarianFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='food',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Ingredient'),
        ),
    ]
